#!/bin/bash

files=(
"Content/WaterEffect/Texture/T_Fx_WaterShape.uasset"
"Content"
"Content/StylizedHalloweenPack"
"Content/StylizedHalloweenPack/Textures"
"Content/StylizedHalloweenPack/Textures/Puppy"
"Content/StylizedHalloweenPack/Textures/Puppy/T_HalloweenPuppy_E.uasset"
"Content/StylizedHalloweenPack/Textures/Puppy/T_HalloweenPuppy_Gn_D.uasset"
"Content/StylizedHalloweenPack/Textures/Puppy/T_HalloweenPuppy_Gr_D.uasset"
"Content/StylizedHalloweenPack/Textures/Puppy/T_HalloweenPuppy_ORM.uasset"
"Content/StylizedHalloweenPack/Textures/Puppy/T_HalloweenPuppy_Pe_D.uasset"
"Content/ThirdPerson"
"Content/ThirdPerson/Blueprints"
"Content/ThirdPerson/Blueprints/BP_ThirdPersonCharacter.uasset"
"Content/ThirdPerson/Input"
"Content/ThirdPerson/Input/Actions"
"Content/ThirdPerson/Input/Actions/IA_Jump.uasset"
"Content/ThirdPerson/Input/Actions/IA_Look.uasset"
"Content/ThirdPerson/Input/Actions/IA_Move.uasset"
"Content/ThirdPerson/Input/IMC_Default.uasset"
"Content/ThirdPerson/Maps"
"Content/ThirdPerson/Maps/ThirdPersonMap.umap"
"Content/ThirdPerson/Maps/ThirdPersonMap_BuiltData.uasset"
"Content/WaterEffect"
"Content/WaterEffect/Common"
"Content/WaterEffect/Common/Material"
"Content/WaterEffect/Common/Material/Curve"
"Content/WaterEffect/Common/Material/Curve/CurveLinearColorAtlas.uasset"
"Content/WaterEffect/Common/Material/Curve/CV_Fx_FireA.uasset"
"Content/WaterEffect/Common/Material/Curve/CV_Fx_FireB.uasset"
"Content/WaterEffect/Common/Material/Curve/CV_Fx_GradientA.uasset"
"Content/WaterEffect/Common/Material/Curve/CV_Fx_Lightning.uasset"
"Content/WaterEffect/Common/Material/Curve/CV_Fx_Water.uasset"
"Content/WaterEffect/Common/Material/DefaultTexture"
"Content/WaterEffect/Common/Material/DefaultTexture/T_Fx_C.uasset"
"Content/WaterEffect/Common/Material/DefaultTexture/T_Fx_LC.uasset"
"Content/WaterEffect/Common/Material/DefaultTexture/T_Fx_N.uasset"
"Content/WaterEffect/Common/Material/MaterialFunction"
"Content/WaterEffect/Common/Material/MaterialFunction/MF_Fx_Dissolution.uasset"
"Content/WaterEffect/Common/Material/MaterialFunction/MF_Fx_FinalControl.uasset"
"Content/WaterEffect/Common/Material/MaterialFunction/MF_Fx_UVAnimation.uasset"
"Content/WaterEffect/Common/Material/MaterialFunction/MF_Fx_UVEdgeFade.uasset"
"Content/WaterEffect/Common/Material/MaterialFunction/MF_ParticleColor.uasset"
"Content/WaterEffect/Common/Material/ParentMaterial"
"Content/WaterEffect/Common/Material/ParentMaterial/M_Fx_Common_Base.uasset"
"Content/WaterEffect/Common/Material/ParentMaterial/M_Fx_Common_Usual.uasset"
"Content/WaterEffect/Common/Material/ParentMaterial/M_Fx_Spark.uasset"
"Content/WaterEffect/Level"
"Content/WaterEffect/Level/WaterFxTemplate.umap"
"Content/WaterEffect/Material"
"Content/WaterEffect/Material/M_Fx_Caustics.uasset"
"Content/WaterEffect/Material/MI_Fx_Bubble.uasset"
"Content/WaterEffect/Material/MI_Fx_bubble02.uasset"
"Content/WaterEffect/Material/MI_Fx_Flare01.uasset"
"Content/WaterEffect/Material/MI_Fx_Foam01.uasset"
"Content/WaterEffect/Material/MI_Fx_GlowShape.uasset"
"Content/WaterEffect/Material/MI_Fx_Ray.uasset"
"Content/WaterEffect/Material/MI_Fx_Ray02.uasset"
"Content/WaterEffect/Material/MI_Fx_SeqSpray01.uasset"
"Content/WaterEffect/Material/MI_Fx_SeqWater01.uasset"
"Content/WaterEffect/Material/MI_Fx_Spark.uasset"
"Content/WaterEffect/Material/MI_Fx_Sparkling.uasset"
"Content/WaterEffect/Material/MI_Fx_Spray02.uasset"
"Content/WaterEffect/Material/MI_Fx_Water01.uasset"
"Content/WaterEffect/Material/MI_Fx_Water02.uasset"
"Content/WaterEffect/Niagara"
"Content/WaterEffect/Niagara/NS_Fx_Bubble.uasset"
"Content/WaterEffect/Niagara/NS_Fx_Bubble02.uasset"
"Content/WaterEffect/Niagara/NS_Fx_Caustics.uasset"
"Content/WaterEffect/Niagara/NS_Fx_Foam01.uasset"
"Content/WaterEffect/Niagara/NS_Fx_Ray.uasset"
"Content/WaterEffect/Niagara/NS_Fx_Sparkling.uasset"
"Content/WaterEffect/Niagara/NS_Fx_Spray01.uasset"
"Content/WaterEffect/Niagara/NS_Fx_Spray02.uasset"
"Content/WaterEffect/Niagara/NS_Fx_Water01_Infinite.uasset"
"Content/WaterEffect/Niagara/NS_Fx_Water02_Cone.uasset"
"Content/WaterEffect/Niagara/NS_Fx_Water03_Cone.uasset"
"Content/WaterEffect/Niagara/NS_Fx_Water04_Radial.uasset"
"Content/WaterEffect/Texture"
"Content/WaterEffect/Texture/T_Fx_Bubble01.uasset"
"Content/WaterEffect/Texture/T_Fx_Bubble02.uasset"
"Content/WaterEffect/Texture/T_Fx_Flare11.uasset"
"Content/WaterEffect/Texture/T_Fx_Foam01.uasset"
"Content/WaterEffect/Texture/T_Fx_Foam02.uasset"
"Content/WaterEffect/Texture/T_Fx_FoamShape.uasset"
"Content/WaterEffect/Texture/T_Fx_Gradient01.uasset"
"Content/WaterEffect/Texture/T_Fx_Noise01.uasset"
"Content/WaterEffect/Texture/T_Fx_Noise03.uasset"
"Content/WaterEffect/Texture/T_Fx_Noise04.uasset"
"Content/WaterEffect/Texture/T_Fx_Noise05.uasset"
"Content/WaterEffect/Texture/T_Fx_NoiseC.uasset"
"Content/WaterEffect/Texture/T_Fx_Shape05.uasset"
"Content/WaterEffect/Texture/T_Fx_WarpSphere.uasset"
"Content/WaterEffect/Texture/T_Fx_Water01.uasset"
"Content/WaterEffect/Texture/T_Fx_Water0414.uasset"
)

# Remove files from Git index (unstage & untrack)
for file in "${FILES[@]}"
do
  git rm --cached "$file"
done

# Re-add files to Git LFS tracking
for file in "${FILES[@]}"
do
  git add "$file"
done

echo "Finished removing and re-adding files to Git LFS tracking."


echo "Re-tracking ${#files[@]} broken files with LFS..."

for file in "${files[@]}"; do
  if [[ -f "$file" ]]; then
    echo "Fixing: $file"
    git rm --cached "$file"
    git add "$file"
  else
    echo "Skipped (not found): $file"
  fi
done

echo "✅ Done. Now run: git commit -m 'Fix LFS pointer issues'"